[package]
name = "otterc_lexer"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
otterc_span.path = "../otterc_span"

logos = "0.15"
thiserror = "2"

[lints]
workspace = true
