[package]
name = "otterc_symbol"
version = "0.1.0"
edition = "2024"

[dependencies]
abi_stable.workspace = true
ahash.workspace = true
once_cell.workspace = true
parking_lot.workspace = true

[lints]
workspace = true
