[package]
name = "otterc_lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
otterc_span.path = "../otterc_span"
otterc_utils.path = "../otterc_utils"

logos = "0.16"
thiserror = "2"

[lints]
workspace = true
